#!/bin/bash

python main.py scripts/gridsearch_configs/faces/faces_000.json
python main.py scripts/gridsearch_configs/faces/faces_001.json
python main.py scripts/gridsearch_configs/faces/faces_002.json
python main.py scripts/gridsearch_configs/faces/faces_003.json
python main.py scripts/gridsearch_configs/faces/faces_004.json
python main.py scripts/gridsearch_configs/faces/faces_005.json
python main.py scripts/gridsearch_configs/faces/faces_006.json
python main.py scripts/gridsearch_configs/faces/faces_007.json
python main.py scripts/gridsearch_configs/faces/faces_008.json
python main.py scripts/gridsearch_configs/faces/faces_009.json
python main.py scripts/gridsearch_configs/faces/faces_010.json
python main.py scripts/gridsearch_configs/faces/faces_011.json
python main.py scripts/gridsearch_configs/faces/faces_012.json
python main.py scripts/gridsearch_configs/faces/faces_013.json
python main.py scripts/gridsearch_configs/faces/faces_014.json
python main.py scripts/gridsearch_configs/faces/faces_015.json
python main.py scripts/gridsearch_configs/faces/faces_016.json
python main.py scripts/gridsearch_configs/faces/faces_017.json
python main.py scripts/gridsearch_configs/faces/faces_018.json
python main.py scripts/gridsearch_configs/faces/faces_019.json
python main.py scripts/gridsearch_configs/faces/faces_020.json
python main.py scripts/gridsearch_configs/faces/faces_021.json
python main.py scripts/gridsearch_configs/faces/faces_022.json
python main.py scripts/gridsearch_configs/faces/faces_023.json
python main.py scripts/gridsearch_configs/faces/faces_024.json
python main.py scripts/gridsearch_configs/faces/faces_025.json
python main.py scripts/gridsearch_configs/faces/faces_026.json
python main.py scripts/gridsearch_configs/faces/faces_027.json
python main.py scripts/gridsearch_configs/faces/faces_028.json
python main.py scripts/gridsearch_configs/faces/faces_029.json
python main.py scripts/gridsearch_configs/faces/faces_030.json
python main.py scripts/gridsearch_configs/faces/faces_031.json
python main.py scripts/gridsearch_configs/faces/faces_032.json
python main.py scripts/gridsearch_configs/faces/faces_033.json
python main.py scripts/gridsearch_configs/faces/faces_034.json
python main.py scripts/gridsearch_configs/faces/faces_035.json
python main.py scripts/gridsearch_configs/faces/faces_036.json
python main.py scripts/gridsearch_configs/faces/faces_037.json
python main.py scripts/gridsearch_configs/faces/faces_038.json
python main.py scripts/gridsearch_configs/faces/faces_039.json
python main.py scripts/gridsearch_configs/faces/faces_040.json
python main.py scripts/gridsearch_configs/faces/faces_041.json
python main.py scripts/gridsearch_configs/faces/faces_042.json
python main.py scripts/gridsearch_configs/faces/faces_043.json
python main.py scripts/gridsearch_configs/faces/faces_044.json
python main.py scripts/gridsearch_configs/faces/faces_045.json
python main.py scripts/gridsearch_configs/faces/faces_046.json
python main.py scripts/gridsearch_configs/faces/faces_047.json
python main.py scripts/gridsearch_configs/faces/faces_048.json
python main.py scripts/gridsearch_configs/faces/faces_049.json
python main.py scripts/gridsearch_configs/faces/faces_050.json
python main.py scripts/gridsearch_configs/faces/faces_051.json
python main.py scripts/gridsearch_configs/faces/faces_052.json
python main.py scripts/gridsearch_configs/faces/faces_053.json
python main.py scripts/gridsearch_configs/faces/faces_054.json
python main.py scripts/gridsearch_configs/faces/faces_055.json
python main.py scripts/gridsearch_configs/faces/faces_056.json
python main.py scripts/gridsearch_configs/faces/faces_057.json
python main.py scripts/gridsearch_configs/faces/faces_058.json
python main.py scripts/gridsearch_configs/faces/faces_059.json
python main.py scripts/gridsearch_configs/faces/faces_060.json
python main.py scripts/gridsearch_configs/faces/faces_061.json
python main.py scripts/gridsearch_configs/faces/faces_062.json
python main.py scripts/gridsearch_configs/faces/faces_063.json
python main.py scripts/gridsearch_configs/faces/faces_064.json
python main.py scripts/gridsearch_configs/faces/faces_065.json
python main.py scripts/gridsearch_configs/faces/faces_066.json
python main.py scripts/gridsearch_configs/faces/faces_067.json
python main.py scripts/gridsearch_configs/faces/faces_068.json
python main.py scripts/gridsearch_configs/faces/faces_069.json
python main.py scripts/gridsearch_configs/faces/faces_070.json
python main.py scripts/gridsearch_configs/faces/faces_071.json
python main.py scripts/gridsearch_configs/faces/faces_072.json
python main.py scripts/gridsearch_configs/faces/faces_073.json
python main.py scripts/gridsearch_configs/faces/faces_074.json
python main.py scripts/gridsearch_configs/faces/faces_075.json
python main.py scripts/gridsearch_configs/faces/faces_076.json
python main.py scripts/gridsearch_configs/faces/faces_077.json
python main.py scripts/gridsearch_configs/faces/faces_078.json
python main.py scripts/gridsearch_configs/faces/faces_079.json
python main.py scripts/gridsearch_configs/faces/faces_080.json
python main.py scripts/gridsearch_configs/faces/faces_081.json
python main.py scripts/gridsearch_configs/faces/faces_082.json
python main.py scripts/gridsearch_configs/faces/faces_083.json
python main.py scripts/gridsearch_configs/faces/faces_084.json
